### ISSUE TITLE
sending-forecast 500: numeric[] returned as string by node-postgres (rawDelays.map is not a function)

### ISSUE THREAD

**Issue by KevinLourd** [shamanic-technologies/instantly-service#454]
## Fixed (hotfix v0.59.1, PR #452 → main)

`GET /internal/audit/sending-forecast` was 500ing the whole fleet with `rawDelays.map is not a function` — cascading 502s through email-gateway → features-service → api-service (the staff "Audit → Instantly" send-forecast + the public sending-forecast).

### Root cause (regression from PR #445 / issue #446)
`loadPendingLeads` built the per-step delay array as a Postgres `numeric[]` via `ARRAY(SELECT (elem->>'delay')::numeric ...)`. **node-postgres returns a `numeric[]` as its raw text form (`"{3,7,0}"` — a string), not a parsed JS array.** So the `?? []` guard never fired (a string is truthy) and `rawDelays.map(...)` threw.

- `int[]` from `ARRAY_AGG` (`provisioned_steps`) parses fine, and the per-account queue breakdown selects raw jsonb — so only this `numeric[]` path broke.
- Pure-function unit tests could not catch it: the mis-parse only happens against real node-postgres, not the mocked `db.execute`.

### Fix
Emit the delays as a **JSONB array** (`jsonb_agg`), which node-postgres always parses into a JS array. Preserves the exact "latest config row → its steps" semantics; a null / non-array `steps` yields `[]` (never throws, never fabricates). Plus a defensive `Array.isArray` guard in the mapper so any future shape surprise degrades one lead to the `STEP_GAP` fallback instead of 500ing the fleet forecast.

### Verification
- Fixed query run against prod: returns jsonb arrays (e.g. `[3,7,0]`) for all 6,291 config'd leads, null for the 72 without.
- 645/645 unit tests, `tsc` + build green.
- Prod deploy v0.59.1 (sha 31d1358) **SUCCESS**; main→staging sync PR #453 merged.

### Follow-up
Any future SQL returning a Postgres array to node-postgres for JS consumption should prefer `jsonb_agg` over `ARRAY(...)` — `numeric[]` (and other non-`int4` array OIDs) come back as strings.

Regression of #446 (PR #445).
